networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  best_users_prettier:
    container_name: best_users_prettier
    depends_on:
    - sink
    entrypoint: /prettier
    environment:
    - BESTUSERPRE_WORKERS_POOL=16
    - BESTUSERPRE_RABBITMQ_IP=rabbitmq
    - BESTUSERPRE_RABBITMQ_PORT=5672
    - BESTUSERPRE_MIN_REVIEWS=50
    - BESTUSERPRE_BESTUSER_JOINERS=1
    - BESTUSERPRE_LOG_LEVEL=INFO
    image: best_users_prettier:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  bestuser_joiner0:
    container_name: bestuser_joiner0
    depends_on:
    - best_users_prettier
    entrypoint: /joiner
    environment:
    - BESTUSERJOIN_WORKERS_POOL=16
    - BESTUSERJOIN_LOG_BULK_RATE=25
    - BESTUSERJOIN_INSTANCE=0
    - BESTUSERJOIN_RABBITMQ_IP=rabbitmq
    - BESTUSERJOIN_RABBITMQ_PORT=5672
    - BESTUSERJOIN_INPUT_TOPIC=0
    - BESTUSERJOIN_STARS_AGGREGATORS=1
    - BESTUSERJOIN_USER_FILTERS=1
    - BESTUSERJOIN_LOG_LEVEL=INFO
    image: bestuser_joiner:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  biz_scatter:
    container_name: biz_scatter
    depends_on:
    - citbiz_mapper0
    - citbiz_mapper1
    - citbiz_mapper2
    entrypoint: /scatter
    environment:
    - BIZSCA_WORKERS_POOL=16
    - BIZSCA_LOG_BULK_RATE=25
    - BIZSCA_INSTANCE=0
    - BIZSCA_BUSINESS_DATA=/data/business.json
    - BIZSCA_RABBITMQ_IP=rabbitmq
    - BIZSCA_RABBITMQ_PORT=5672
    - BIZSCA_BULK_SIZE=10000
    - BIZSCA_CITBIZ_MAPPERS=3
    - BIZSCA_LOG_LEVEL=INFO
    image: biz_scatter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
    volumes:
    - business_dataset:/data
  bot_users_prettier:
    container_name: bot_users_prettier
    depends_on:
    - sink
    entrypoint: /prettier
    environment:
    - BOTUSERPRE_WORKERS_POOL=16
    - BOTUSERPRE_RABBITMQ_IP=rabbitmq
    - BOTUSERPRE_RABBITMQ_PORT=5672
    - BOTUSERPRE_MIN_REVIEWS=5
    - BOTUSERPRE_BOTS_AGGREGATORS=1
    - BOTUSERPRE_LOG_LEVEL=INFO
    image: bot_users_prettier:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  bots_aggregator0:
    container_name: bots_aggregator0
    depends_on:
    - bot_users_prettier
    entrypoint: /aggregator
    environment:
    - BOTAGG_WORKERS_POOL=16
    - BOTAGG_LOG_BULK_RATE=25
    - BOTAGG_INSTANCE=0
    - BOTAGG_RABBITMQ_IP=rabbitmq
    - BOTAGG_RABBITMQ_PORT=5672
    - BOTAGG_INPUT_TOPIC=0
    - BOTAGG_HASH_MAPPERS=3
    - BOTAGG_MIN_REVIEWS=5
    - BOTAGG_LOG_LEVEL=INFO
    image: bots_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  citbiz_mapper0:
    container_name: citbiz_mapper0
    depends_on:
    - funcit_joiner0
    entrypoint: /mapper
    environment:
    - CITBIZMAP_WORKERS_POOL=16
    - CITBIZMAP_LOG_BULK_RATE=25
    - CITBIZMAP_INSTANCE=0
    - CITBIZMAP_RABBITMQ_IP=rabbitmq
    - CITBIZMAP_RABBITMQ_PORT=5672
    - CITBIZMAP_BUSINESSES_INPUTS=1
    - CITBIZMAP_FUNCIT_JOINERS=1
    - CITBIZMAP_LOG_LEVEL=INFO
    image: citbiz_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  citbiz_mapper1:
    container_name: citbiz_mapper1
    depends_on:
    - funcit_joiner0
    entrypoint: /mapper
    environment:
    - CITBIZMAP_WORKERS_POOL=16
    - CITBIZMAP_LOG_BULK_RATE=25
    - CITBIZMAP_INSTANCE=1
    - CITBIZMAP_RABBITMQ_IP=rabbitmq
    - CITBIZMAP_RABBITMQ_PORT=5672
    - CITBIZMAP_BUSINESSES_INPUTS=1
    - CITBIZMAP_FUNCIT_JOINERS=1
    - CITBIZMAP_LOG_LEVEL=INFO
    image: citbiz_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  citbiz_mapper2:
    container_name: citbiz_mapper2
    depends_on:
    - funcit_joiner0
    entrypoint: /mapper
    environment:
    - CITBIZMAP_WORKERS_POOL=16
    - CITBIZMAP_LOG_BULK_RATE=25
    - CITBIZMAP_INSTANCE=2
    - CITBIZMAP_RABBITMQ_IP=rabbitmq
    - CITBIZMAP_RABBITMQ_PORT=5672
    - CITBIZMAP_BUSINESSES_INPUTS=1
    - CITBIZMAP_FUNCIT_JOINERS=1
    - CITBIZMAP_LOG_LEVEL=INFO
    image: citbiz_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_aggregator0:
    container_name: funbiz_aggregator0
    depends_on:
    - funcit_joiner0
    entrypoint: /aggregator
    environment:
    - FUNBIZAGG_WORKERS_POOL=16
    - FUNBIZAGG_LOG_BULK_RATE=25
    - FUNBIZAGG_INSTANCE=0
    - FUNBIZAGG_RABBITMQ_IP=rabbitmq
    - FUNBIZAGG_RABBITMQ_PORT=5672
    - FUNBIZAGG_FUNBIZ_FILTERS=1
    - FUNBIZAGG_FUNCIT_JOINERS=1
    - FUNBIZAGG_INPUT_TOPIC=0
    - FUNBIZAGG_OUTPUT_BULK_SIZE=10000
    - FUNBIZAGG_LOG_LEVEL=INFO
    image: funbiz_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_filter0:
    container_name: funbiz_filter0
    depends_on:
    - funbiz_aggregator0
    entrypoint: /filter
    environment:
    - FUNBIZFIL_WORKERS_POOL=16
    - FUNBIZFIL_LOG_BULK_RATE=25
    - FUNBIZFIL_INSTANCE=0
    - FUNBIZFIL_RABBITMQ_IP=rabbitmq
    - FUNBIZFIL_RABBITMQ_PORT=5672
    - FUNBIZFIL_FUNBIZ_MAPPERS=2
    - FUNBIZFIL_FUNBIZ_AGGREGATORS=1
    - FUNBIZFIL_LOG_LEVEL=INFO
    image: funbiz_filter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_mapper0:
    container_name: funbiz_mapper0
    depends_on:
    - funbiz_filter0
    entrypoint: /mapper
    environment:
    - FUNBIZMAP_WORKERS_POOL=16
    - FUNBIZMAP_LOG_BULK_RATE=25
    - FUNBIZMAP_INSTANCE=0
    - FUNBIZMAP_RABBITMQ_IP=rabbitmq
    - FUNBIZMAP_RABBITMQ_PORT=5672
    - FUNBIZMAP_REVIEWS_INPUTS=1
    - FUNBIZMAP_FUNBIZ_FILTERS=1
    - FUNBIZMAP_LOG_LEVEL=INFO
    image: funbiz_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funbiz_mapper1:
    container_name: funbiz_mapper1
    depends_on:
    - funbiz_filter0
    entrypoint: /mapper
    environment:
    - FUNBIZMAP_WORKERS_POOL=16
    - FUNBIZMAP_LOG_BULK_RATE=25
    - FUNBIZMAP_INSTANCE=1
    - FUNBIZMAP_RABBITMQ_IP=rabbitmq
    - FUNBIZMAP_RABBITMQ_PORT=5672
    - FUNBIZMAP_REVIEWS_INPUTS=1
    - FUNBIZMAP_FUNBIZ_FILTERS=1
    - FUNBIZMAP_LOG_LEVEL=INFO
    image: funbiz_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funcit_joiner0:
    container_name: funcit_joiner0
    depends_on:
    - funcit_top0
    entrypoint: /joiner
    environment:
    - FUNCITJOIN_WORKERS_POOL=16
    - FUNCITJOIN_LOG_BULK_RATE=25
    - FUNCITJOIN_INSTANCE=0
    - FUNCITJOIN_RABBITMQ_IP=rabbitmq
    - FUNCITJOIN_RABBITMQ_PORT=5672
    - FUNCITJOIN_FUNBIZ_AGGREGATORS=1
    - FUNCITJOIN_CITBIZ_MAPPERS=3
    - FUNCITJOIN_FUNCIT_TOPS=1
    - FUNCITJOIN_INPUT_TOPIC=0
    - FUNCITJOIN_OUTPUT_BULK_SIZE=10000
    - FUNCITJOIN_LOG_LEVEL=INFO
    image: funcit_joiner:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  funcit_top0:
    container_name: funcit_top0
    depends_on:
    - top_funniest_cities_prettier
    entrypoint: /aggregator
    environment:
    - FUNCITTOP_WORKERS_POOL=16
    - FUNCITTOP_LOG_BULK_RATE=25
    - FUNCITTOP_INSTANCE=0
    - FUNCITTOP_RABBITMQ_IP=rabbitmq
    - FUNCITTOP_RABBITMQ_PORT=5672
    - FUNCITTOP_TOP_SIZE=10
    - FUNCITTOP_FUNCIT_JOINERS=1
    - FUNCITTOP_LOG_LEVEL=INFO
    - FUNCITTOP_INPUT_TOPIC=0
    image: funcit_top:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  hash_mapper0:
    container_name: hash_mapper0
    depends_on:
    - bots_aggregator0
    entrypoint: /mapper
    environment:
    - HASHMAP_WORKERS_POOL=16
    - HASHMAP_LOG_BULK_RATE=25
    - HASHMAP_INSTANCE=0
    - HASHMAP_RABBITMQ_IP=rabbitmq
    - HASHMAP_RABBITMQ_PORT=5672
    - HASHMAP_REVIEWS_INPUTS=1
    - HASHMAP_BOTS_AGGREGATORS=1
    - HASHMAP_LOG_LEVEL=INFO
    image: hash_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  hash_mapper1:
    container_name: hash_mapper1
    depends_on:
    - bots_aggregator0
    entrypoint: /mapper
    environment:
    - HASHMAP_WORKERS_POOL=16
    - HASHMAP_LOG_BULK_RATE=25
    - HASHMAP_INSTANCE=1
    - HASHMAP_RABBITMQ_IP=rabbitmq
    - HASHMAP_RABBITMQ_PORT=5672
    - HASHMAP_REVIEWS_INPUTS=1
    - HASHMAP_BOTS_AGGREGATORS=1
    - HASHMAP_LOG_LEVEL=INFO
    image: hash_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  hash_mapper2:
    container_name: hash_mapper2
    depends_on:
    - bots_aggregator0
    entrypoint: /mapper
    environment:
    - HASHMAP_WORKERS_POOL=16
    - HASHMAP_LOG_BULK_RATE=25
    - HASHMAP_INSTANCE=2
    - HASHMAP_RABBITMQ_IP=rabbitmq
    - HASHMAP_RABBITMQ_PORT=5672
    - HASHMAP_REVIEWS_INPUTS=1
    - HASHMAP_BOTS_AGGREGATORS=1
    - HASHMAP_LOG_LEVEL=INFO
    image: hash_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  rabbitmq:
    container_name: rabbitmq
    healthcheck:
      interval: 10s
      retries: '10'
      test: '["CMD", "curl", "-f", "http://rabbitmq:156722]'
      timeout: 5s
    image: rabbitmq:custom
    logging:
      driver: none
    networks:
    - testing_net
    ports:
    - 15672:15672
    - 5672:5672
  sink:
    container_name: sink
    depends_on:
    - rabbitmq
    entrypoint: /sink
    environment:
    - SINK_RABBITMQ_IP=rabbitmq
    - SINK_RABBITMQ_PORT=5672
    - SINK_LOG_LEVEL=INFO
    image: sink:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  stars_aggregator0:
    container_name: stars_aggregator0
    depends_on:
    - bestuser_joiner0
    entrypoint: /aggregator
    environment:
    - STARSAGG_WORKERS_POOL=16
    - STARSAGG_LOG_BULK_RATE=25
    - STARSAGG_INSTANCE=0
    - STARSAGG_RABBITMQ_IP=rabbitmq
    - STARSAGG_RABBITMQ_PORT=5672
    - STARSAGG_INPUT_TOPIC=0
    - STARSAGG_STARS_FILTERS=1
    - STARSAGG_STARS_JOINERS=1
    - STARSAGG_OUTPUT_BULK_SIZE=10000
    - STARSAGG_LOG_LEVEL=INFO
    image: stars_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  stars_filter0:
    container_name: stars_filter0
    depends_on:
    - stars_aggregator0
    entrypoint: /filter
    environment:
    - STARSFIL_WORKERS_POOL=16
    - STARSFIL_LOG_BULK_RATE=25
    - STARSFIL_INSTANCE=0
    - STARSFIL_RABBITMQ_IP=rabbitmq
    - STARSFIL_RABBITMQ_PORT=5672
    - STARSFIL_STARS_MAPPERS=2
    - STARSFIL_STARS_AGGREGATORS=1
    - STARSFIL_LOG_LEVEL=INFO
    image: stars_filter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  stars_mapper0:
    container_name: stars_mapper0
    depends_on:
    - stars_filter0
    entrypoint: /mapper
    environment:
    - STARSMAP_WORKERS_POOL=16
    - STARSMAP_LOG_BULK_RATE=25
    - STARSMAP_INSTANCE=0
    - STARSMAP_RABBITMQ_IP=rabbitmq
    - STARSMAP_RABBITMQ_PORT=5672
    - STARSMAP_REVIEWS_INPUTS=1
    - STARSMAP_STARS_FILTERS=1
    - STARSMAP_LOG_LEVEL=INFO
    image: stars_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  stars_mapper1:
    container_name: stars_mapper1
    depends_on:
    - stars_filter0
    entrypoint: /mapper
    environment:
    - STARSMAP_WORKERS_POOL=16
    - STARSMAP_LOG_BULK_RATE=25
    - STARSMAP_INSTANCE=1
    - STARSMAP_RABBITMQ_IP=rabbitmq
    - STARSMAP_RABBITMQ_PORT=5672
    - STARSMAP_REVIEWS_INPUTS=1
    - STARSMAP_STARS_FILTERS=1
    - STARSMAP_LOG_LEVEL=INFO
    image: stars_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  top_funniest_cities_prettier:
    container_name: top_funniest_cities_prettier
    depends_on:
    - sink
    entrypoint: /prettier
    environment:
    - FUNCITPRE_WORKERS_POOL=16
    - FUNCITPRE_RABBITMQ_IP=rabbitmq
    - FUNCITPRE_RABBITMQ_PORT=5672
    - FUNCITPRE_TOP_SIZE=10
    - FUNCITPRE_FUNCIT_TOPS=1
    - FUNCITPRE_LOG_LEVEL=INFO
    image: top_funniest_cities_prettier:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  top_users_prettier:
    container_name: top_users_prettier
    depends_on:
    - sink
    entrypoint: /prettier
    environment:
    - TOPUSERPRE_WORKERS_POOL=16
    - TOPUSERPRE_LOG_BULK_RATE=25
    - TOPUSERPRE_RABBITMQ_IP=rabbitmq
    - TOPUSERPRE_RABBITMQ_PORT=5672
    - TOPUSERPRE_MIN_REVIEWS=50
    - TOPUSERPRE_USER_FILTERS=1
    - TOPUSERPRE_LOG_LEVEL=INFO
    image: top_users_prettier:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  user_aggregator0:
    container_name: user_aggregator0
    depends_on:
    - user_filter0
    entrypoint: /aggregator
    environment:
    - USERAGG_WORKERS_POOL=16
    - USERAGG_LOG_BULK_RATE=25
    - USERAGG_INSTANCE=0
    - USERAGG_RABBITMQ_IP=rabbitmq
    - USERAGG_RABBITMQ_PORT=5672
    - USERAGG_INPUT_TOPIC=0
    - USERAGG_USER_MAPPERS=2
    - USERAGG_USER_FILTERS=1
    - USERAGG_OUTPUT_BULK_SIZE=10000
    - USERAGG_LOG_LEVEL=INFO
    image: user_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  user_filter0:
    container_name: user_filter0
    depends_on:
    - bestuser_joiner0
    - top_users_prettier
    entrypoint: /filter
    environment:
    - USERFIL_WORKERS_POOL=16
    - USERFIL_LOG_BULK_RATE=25
    - USERFIL_INSTANCE=0
    - USERFIL_RABBITMQ_IP=rabbitmq
    - USERFIL_RABBITMQ_PORT=5672
    - USERFIL_MIN_REVIEWS=50
    - USERFIL_USER_AGGREGATORS=1
    - USERFIL_STARS_JOINERS=1
    - USERFIL_LOG_LEVEL=INFO
    image: user_filter:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  user_mapper0:
    container_name: user_mapper0
    depends_on:
    - user_aggregator0
    entrypoint: /mapper
    environment:
    - USERMAP_WORKERS_POOL=16
    - USERMAP_LOG_BULK_RATE=25
    - USERMAP_INSTANCE=0
    - USERMAP_RABBITMQ_IP=rabbitmq
    - USERMAP_RABBITMQ_PORT=5672
    - USERMAP_REVIEWS_INPUTS=1
    - USERMAP_USER_AGGREGATORS=1
    - USERMAP_LOG_LEVEL=INFO
    image: user_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  user_mapper1:
    container_name: user_mapper1
    depends_on:
    - user_aggregator0
    entrypoint: /mapper
    environment:
    - USERMAP_WORKERS_POOL=16
    - USERMAP_LOG_BULK_RATE=25
    - USERMAP_INSTANCE=1
    - USERMAP_RABBITMQ_IP=rabbitmq
    - USERMAP_RABBITMQ_PORT=5672
    - USERMAP_REVIEWS_INPUTS=1
    - USERMAP_USER_AGGREGATORS=1
    - USERMAP_LOG_LEVEL=INFO
    image: user_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_aggregator0:
    container_name: weekday_aggregator0
    depends_on:
    - weekday_histogram_prettier
    entrypoint: /aggregator
    environment:
    - WEEKDAYAGG_WORKERS_POOL=16
    - WEEKDAYAGG_LOG_BULK_RATE=25
    - WEEKDAYAGG_INSTANCE=0
    - WEEKDAYAGG_RABBITMQ_IP=rabbitmq
    - WEEKDAYAGG_RABBITMQ_PORT=5672
    - WEEKDAYAGG_INPUT_TOPIC=0
    - WEEKDAYAGG_WEEKDAY_MAPPERS=2
    - WEEKDAYAGG_LOG_LEVEL=INFO
    image: weekday_aggregator:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_histogram_prettier:
    container_name: weekday_histogram_prettier
    depends_on:
    - sink
    entrypoint: /prettier
    environment:
    - HISTOPRE_WORKERS_POOL=16
    - HISTOPRE_INSTANCE=0
    - HISTOPRE_RABBITMQ_IP=rabbitmq
    - HISTOPRE_RABBITMQ_PORT=5672
    - HISTOPRE_WEEKDAY_AGGREGATORS=1
    - HISTOPRE_LOG_LEVEL=INFO
    image: weekday_histogram_prettier:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_mapper0:
    container_name: weekday_mapper0
    depends_on:
    - weekday_aggregator0
    entrypoint: /mapper
    environment:
    - WEEKDAYMAP_WORKERS_POOL=16
    - WEEKDAYMAP_LOG_BULK_RATE=25
    - WEEKDAYMAP_INSTANCE=0
    - WEEKDAYMAP_RABBITMQ_IP=rabbitmq
    - WEEKDAYMAP_RABBITMQ_PORT=5672
    - WEEKDAYMAP_REVIEWS_INPUTS=1
    - WEEKDAYMAP_WEEKDAY_AGGREGATORS=1
    - WEEKDAYMAP_LOG_LEVEL=INFO
    image: weekday_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
  weekday_mapper1:
    container_name: weekday_mapper1
    depends_on:
    - weekday_aggregator0
    entrypoint: /mapper
    environment:
    - WEEKDAYMAP_WORKERS_POOL=16
    - WEEKDAYMAP_LOG_BULK_RATE=25
    - WEEKDAYMAP_INSTANCE=1
    - WEEKDAYMAP_RABBITMQ_IP=rabbitmq
    - WEEKDAYMAP_RABBITMQ_PORT=5672
    - WEEKDAYMAP_REVIEWS_INPUTS=1
    - WEEKDAYMAP_WEEKDAY_AGGREGATORS=1
    - WEEKDAYMAP_LOG_LEVEL=INFO
    image: weekday_mapper:latest
    links:
    - rabbitmq
    networks:
    - testing_net
    restart: on-failure
version: '3'
volumes:
  business_dataset:
    driver: local
    driver_opts:
      device: $PWD/data/business
      o: bind
      type: none
