## Environment
# Logging
log_level: "INFO"
log_bulk_rate: 25

# Flows
funbiz_logging: true
weekday_logging: true
best_logging: true
bots_logging: true
top_logging: true
monitors_logging: true

# Specs
funbiz_top_size: 10
bots_reviews_threshold: 5
users_reviews_threshold: 50

## Nodes
# System
reviews_streaming: false
common_pool_size: 16
monitor_interval: 5

# Bulks
input1_bulk_size: 10000
joiner1_bulk_size: 10000
aggregator1_bulk_size: 10000
aggregator7_bulk_size: 10000
aggregator8_bulk_size: 10000

## Instances
# Mappers
mapper1_instances: 3
mapper2_instances: 2
mapper3_instances: 2
mapper4_instances: 3
mapper5_instances: 2
mapper6_instances: 2

# Filters
filter1_instances: 3
filter4_instances: 1
filter5_instances: 2

# Monitor
monitor_instances: 5
